apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockserver
  namespace: mockserver-ns
  labels:
    app: mockserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockserver
  template:
    metadata:
      labels:
        app: mockserver
    spec:
      containers:
        - name: mockserver
          image: shashank752/experiment:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: db-storage
              mountPath: /app/mock.db
              subPath: mock.db
      volumes:
        - name: db-storage
          emptyDir: {}
