apiVersion: v1
kind: Service
metadata:
  name: mockserver-service
  namespace: mockserver-ns
spec:
  selector:
    app: mockserver
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8000

