apiVersion: v1
kind: Service
metadata:
  name: mockserver
  namespace: mockserver
spec:
  selector:
    app: mockserver
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort